export const SKILLS_TAXONOMY = [
  // ─── Frontend ────────────────────────────────────────────
  { name: 'React', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Vue.js', category: 'Frontend' },
  { name: 'Nuxt.js', category: 'Frontend' },
  { name: 'Angular', category: 'Frontend' },
  { name: 'Svelte', category: 'Frontend' },
  { name: 'SvelteKit', category: 'Frontend' },
  { name: 'Solid.js', category: 'Frontend' },
  { name: 'TypeScript', category: 'Frontend' },
  { name: 'JavaScript', category: 'Frontend' },
  { name: 'HTML', category: 'Frontend' },
  { name: 'CSS', category: 'Frontend' },
  { name: 'SCSS', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Bootstrap', category: 'Frontend' },
  { name: 'Material UI', category: 'Frontend' },
  { name: 'Shadcn UI', category: 'Frontend' },
  { name: 'Radix UI', category: 'Frontend' },
  { name: 'Framer Motion', category: 'Frontend' },
  { name: 'Redux', category: 'Frontend' },
  { name: 'Zustand', category: 'Frontend' },
  { name: 'TanStack Query', category: 'Frontend' },
  { name: 'SWR', category: 'Frontend' },
  { name: 'GraphQL', category: 'Frontend' },
  { name: 'Apollo Client', category: 'Frontend' },
  { name: 'Relay', category: 'Frontend' },
  { name: 'tRPC', category: 'Frontend' },
  { name: 'WebSockets', category: 'Frontend' },
  { name: 'WebRTC', category: 'Frontend' },
  { name: 'PWA', category: 'Frontend' },
  { name: 'Accessibility', category: 'Frontend' },
  { name: 'Responsive Design', category: 'Frontend' },
  { name: 'Browser Extensions', category: 'Frontend' },
  { name: 'Storybook', category: 'Frontend' },
  { name: 'Playwright', category: 'Frontend' },
  { name: 'Cypress', category: 'Frontend' },
  { name: 'Vitest', category: 'Frontend' },
  { name: 'Jest', category: 'Frontend' },

  // ─── Backend ────────────────────────────────────────────
  { name: 'Node.js', category: 'Backend' },
  { name: 'NestJS', category: 'Backend' },
  { name: 'Express', category: 'Backend' },
  { name: 'Fastify', category: 'Backend' },
  { name: 'Python', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'Go', category: 'Backend' },
  { name: 'Rust', category: 'Backend' },
  { name: 'Java', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: 'Kotlin', category: 'Backend' },
  { name: 'Ruby', category: 'Backend' },
  { name: 'Ruby on Rails', category: 'Backend' },
  { name: 'PHP', category: 'Backend' },
  { name: 'Laravel', category: 'Backend' },
  { name: 'Symfony', category: 'Backend' },
  { name: 'C#', category: 'Backend' },
  { name: '.NET', category: 'Backend' },
  { name: 'ASP.NET Core', category: 'Backend' },
  { name: 'Elixir', category: 'Backend' },
  { name: 'Phoenix', category: 'Backend' },
  { name: 'Scala', category: 'Backend' },
  { name: 'Haskell', category: 'Backend' },
  { name: 'REST API', category: 'Backend' },
  { name: 'GraphQL API', category: 'Backend' },
  { name: 'gRPC', category: 'Backend' },
  { name: 'WebSocket API', category: 'Backend' },
  { name: 'JWT', category: 'Backend' },
  { name: 'OAuth 2.0', category: 'Backend' },
  { name: 'OpenID Connect', category: 'Backend' },
  { name: 'Session Management', category: 'Backend' },
  { name: 'Rate Limiting', category: 'Backend' },
  { name: 'Caching', category: 'Backend' },
  { name: 'Redis', category: 'Backend' },
  { name: 'BullMQ', category: 'Backend' },
  { name: 'RabbitMQ', category: 'Backend' },
  { name: 'Kafka', category: 'Backend' },
  { name: 'Serverless', category: 'Backend' },
  { name: 'AWS Lambda', category: 'Backend' },

  // ─── Database ───────────────────────────────────────────
  { name: 'PostgreSQL', category: 'Database' },
  { name: 'MySQL', category: 'Database' },
  { name: 'SQLite', category: 'Database' },
  { name: 'MongoDB', category: 'Database' },
  { name: 'Prisma', category: 'Database' },
  { name: 'TypeORM', category: 'Database' },
  { name: 'Drizzle', category: 'Database' },
  { name: 'Kysely', category: 'Database' },
  { name: 'SQL', category: 'Database' },
  { name: 'Database Design', category: 'Database' },
  { name: 'Query Optimization', category: 'Database' },
  { name: 'Redis', category: 'Database' },
  { name: 'Elasticsearch', category: 'Database' },
  { name: 'Supabase', category: 'Database' },
  { name: 'Firebase Firestore', category: 'Database' },
  { name: 'DynamoDB', category: 'Database' },
  { name: 'Cassandra', category: 'Database' },
  { name: 'Neo4j', category: 'Database' },
  { name: 'ClickHouse', category: 'Database' },

  // ─── DevOps ─────────────────────────────────────────────
  { name: 'Docker', category: 'DevOps' },
  { name: 'Kubernetes', category: 'DevOps' },
  { name: 'Terraform', category: 'DevOps' },
  { name: 'Ansible', category: 'DevOps' },
  { name: 'CI/CD', category: 'DevOps' },
  { name: 'GitHub Actions', category: 'DevOps' },
  { name: 'GitLab CI', category: 'DevOps' },
  { name: 'Jenkins', category: 'DevOps' },
  { name: 'Nginx', category: 'DevOps' },
  { name: 'Linux', category: 'DevOps' },
  { name: 'System Administration', category: 'DevOps' },
  { name: 'Cloud Infrastructure', category: 'DevOps' },
  { name: 'AWS', category: 'DevOps' },
  { name: 'GCP', category: 'DevOps' },
  { name: 'Azure', category: 'DevOps' },
  { name: 'DigitalOcean', category: 'DevOps' },
  { name: 'Vercel', category: 'DevOps' },
  { name: 'Netlify', category: 'DevOps' },
  { name: 'Cloudflare', category: 'DevOps' },
  { name: 'Monitoring', category: 'DevOps' },
  { name: 'Prometheus', category: 'DevOps' },
  { name: 'Grafana', category: 'DevOps' },
  { name: 'Sentry', category: 'DevOps' },
  { name: 'Datadog', category: 'DevOps' },
  { name: 'New Relic', category: 'DevOps' },
  { name: 'Logging', category: 'DevOps' },
  { name: 'ELK Stack', category: 'DevOps' },
  { name: 'OpenTelemetry', category: 'DevOps' },

  // ─── Mobile ────────────────────────────────────────────
  { name: 'React Native', category: 'Mobile' },
  { name: 'Expo', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'Dart', category: 'Mobile' },
  { name: 'Swift', category: 'Mobile' },
  { name: 'SwiftUI', category: 'Mobile' },
  { name: 'iOS Development', category: 'Mobile' },
  { name: 'Kotlin Multiplatform', category: 'Mobile' },
  { name: 'Android Development', category: 'Mobile' },
  { name: 'Jetpack Compose', category: 'Mobile' },
  { name: 'Mobile UI Design', category: 'Mobile' },
  { name: 'App Store Optimization', category: 'Mobile' },

  // ─── Design ───────────────────────────────────────────
  { name: 'UI Design', category: 'Design' },
  { name: 'UX Design', category: 'Design' },
  { name: 'Figma', category: 'Design' },
  { name: 'Sketch', category: 'Design' },
  { name: 'Adobe XD', category: 'Design' },
  { name: 'Adobe Photoshop', category: 'Design' },
  { name: 'Adobe Illustrator', category: 'Design' },
  { name: 'Adobe After Effects', category: 'Design' },
  { name: 'Blender', category: 'Design' },
  { name: '3D Modeling', category: 'Design' },
  { name: 'Motion Design', category: 'Design' },
  { name: 'Typography', category: 'Design' },
  { name: 'Color Theory', category: 'Design' },
  { name: 'Design Systems', category: 'Design' },
  { name: 'Wireframing', category: 'Design' },
  { name: 'Prototyping', category: 'Design' },
  { name: 'User Research', category: 'Design' },
  { name: 'Information Architecture', category: 'Design' },
  { name: 'Interaction Design', category: 'Design' },
  { name: 'Visual Design', category: 'Design' },
  { name: 'Brand Identity', category: 'Design' },
  { name: 'Logo Design', category: 'Design' },

  // ─── Blockchain / Web3 ──────────────────────────────────
  { name: 'Solidity', category: 'Blockchain' },
  { name: 'Ethereum', category: 'Blockchain' },
  { name: 'Smart Contracts', category: 'Blockchain' },
  { name: 'Web3.js', category: 'Blockchain' },
  { name: 'Ethers.js', category: 'Blockchain' },
  { name: 'Stellar', category: 'Blockchain' },
  { name: 'Soroban', category: 'Blockchain' },
  { name: 'Rust', category: 'Blockchain' },
  { name: 'WASM', category: 'Blockchain' },
  { name: 'DeFi', category: 'Blockchain' },
  { name: 'NFT', category: 'Blockchain' },
  { name: 'IPFS', category: 'Blockchain' },
  { name: 'Wallet Integration', category: 'Blockchain' },

  // ─── AI / Machine Learning ─────────────────────────────
  { name: 'Machine Learning', category: 'AI/ML' },
  { name: 'Deep Learning', category: 'AI/ML' },
  { name: 'LLM Integration', category: 'AI/ML' },
  { name: 'OpenAI API', category: 'AI/ML' },
  { name: 'LangChain', category: 'AI/ML' },
  { name: 'RAG', category: 'AI/ML' },
  { name: 'Prompt Engineering', category: 'AI/ML' },
  { name: 'TensorFlow', category: 'AI/ML' },
  { name: 'PyTorch', category: 'AI/ML' },
  { name: 'Scikit-learn', category: 'AI/ML' },
  { name: 'Natural Language Processing', category: 'AI/ML' },
  { name: 'Computer Vision', category: 'AI/ML' },
  { name: 'Data Science', category: 'AI/ML' },
  { name: 'Data Analysis', category: 'AI/ML' },
  { name: 'Python', category: 'AI/ML' },
  { name: 'Jupyter', category: 'AI/ML' },
  { name: 'R', category: 'AI/ML' },

  // ─── Testing ───────────────────────────────────────────
  { name: 'Unit Testing', category: 'Testing' },
  { name: 'Integration Testing', category: 'Testing' },
  { name: 'E2E Testing', category: 'Testing' },
  { name: 'TDD', category: 'Testing' },
  { name: 'Jest', category: 'Testing' },
  { name: 'Vitest', category: 'Testing' },
  { name: 'Mocha', category: 'Testing' },
  { name: 'Cypress', category: 'Testing' },
  { name: 'Playwright', category: 'Testing' },
  { name: 'Puppeteer', category: 'Testing' },
  { name: 'Selenium', category: 'Testing' },
  { name: 'Postman', category: 'Testing' },
  { name: 'API Testing', category: 'Testing' },
  { name: 'Performance Testing', category: 'Testing' },
  { name: 'Security Testing', category: 'Testing' },

  // ─── Project Management ─────────────────────────────────
  { name: 'Agile', category: 'Project Management' },
  { name: 'Scrum', category: 'Project Management' },
  { name: 'Kanban', category: 'Project Management' },
  { name: 'Jira', category: 'Project Management' },
  { name: 'Linear', category: 'Project Management' },
  { name: 'Asana', category: 'Project Management' },
  { name: 'Notion', category: 'Project Management' },
  { name: 'Confluence', category: 'Project Management' },
  { name: 'Technical Writing', category: 'Project Management' },
  { name: 'API Documentation', category: 'Project Management' },
  { name: 'Swagger', category: 'Project Management' },

  // ─── Other ─────────────────────────────────────────────
  { name: 'Git', category: 'Other' },
  { name: 'GitHub', category: 'Other' },
  { name: 'GitLab', category: 'Other' },
  { name: 'Bitbucket', category: 'Other' },
  { name: 'npm', category: 'Other' },
  { name: 'Yarn', category: 'Other' },
  { name: 'pnpm', category: 'Other' },
  { name: 'Bun', category: 'Other' },
  { name: 'Webpack', category: 'Other' },
  { name: 'Vite', category: 'Other' },
  { name: 'Turbopack', category: 'Other' },
  { name: 'ESBuild', category: 'Other' },
  { name: 'Nx', category: 'Other' },
  { name: 'Turborepo', category: 'Other' },
  { name: 'Monorepo', category: 'Other' },
  { name: 'Microservices', category: 'Other' },
  { name: 'Event-Driven Architecture', category: 'Other' },
  { name: 'Domain-Driven Design', category: 'Other' },
  { name: 'Clean Architecture', category: 'Other' },
  { name: 'SOLID Principles', category: 'Other' },
  { name: 'Design Patterns', category: 'Other' },
  { name: 'Algorithms', category: 'Other' },
  { name: 'Data Structures', category: 'Other' },
  { name: 'System Design', category: 'Other' },
  { name: 'SEO', category: 'Other' },
  { name: 'Analytics', category: 'Other' },
  { name: 'A/B Testing', category: 'Other' },
  { name: 'Copywriting', category: 'Other' },
  { name: 'Content Writing', category: 'Other' },
  { name: 'Translation', category: 'Other' },
];
